name: pure_ftp
description: Simple and powerful FTP client for Dart. Allow you to connect to FTP server and perform basic operations. now supports all native platforms(Web in progress)
version: 0.5.2
homepage: https://github.com/crifurch/pure_ftp

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  meta: ^1.10.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
  yaml: ^3.1.2
